### ISSUE TITLE
JPEG XT profile c encoding - inverted base image

### ISSUE THREAD

**Issue by Kamalavasan** [thorfdbg/libjpeg#10]
[images.zip](https://github.com/thorfdbg/libjpeg/files/924458/images.zip)
Dear Dr.Ritcher,
I did JPEG XT profile c encoding using reference software. But it seems output base image is inverted and mirrored one of original HDR image. I have attached images.zip file which contain original image which is  beach_probe.pfm and profile c encoded image is beach_probe_c.jpg. can you please help to get correct base image?

Regards,
K.Kamalavasan

**Comment by thorfdbg** [comment]
Mr. Kamalavasan,
>
> I did JPEG XT profile c encoding using reference software. But it
> seems output base image is inverted and mirrored one of original HDR
> image. I have attached images.zip file which contain original image
> which is beach_probe.pfm and profile c encoded image is
> beach_probe_c.jpg. can you please help to get correct base image?
>

The vertical inversion is due to an inconsistency between pfm images
generated by some programs and the ppm format family that
is able to represent integer samples only. For reasons unclear to me,
some programs save pfm images "upside down", i.e. with the
first data block representing the bottom of the image. The
implementation at hand can only handle images that are correctly
oriented, i.e. with the first data block representing the topmost line
of the image.

If you receive incorrectly oriented images, you find the "difftest_ng"
utility on my github page that is capable to correct this, namely by

difftest_ng --flipy --convert output.pfm input.pfm -

(note the final dash).

Greetings,

Thomas

**Comment by Jamaika1** [comment]
My file pmf convert to jpeg
https://www.sendspace.com/filegroup/nZdkHSNd97x3HwP4VlvCijFT1XS3Z23PmNLQyl4GKBaCBztEalt%2BaQKHZNv5G98T

**Comment by Kamalavasan** [comment]
Dear Dr. Thomas,
yes, now i am able to get correct base image. it is working.
Thanks a lot

**Comment by Kamalavasan** [comment]
thank you Jamaika1

**Comment by oumaima78** [comment]
hello ,could you help me please to solve this problem :when I try to compress a HDR image using this command : $ jpeg -r -q 20 -Q 5 -h -profile c -rR 4 chairs.pfm chairs20_5.jpg
It tolds me that" no command jpeg is found"
what should I do?
I am using ubuntu 16.04
