### ISSUE TITLE
Cannot round-trip RGB / 8bits / interleave none

### ISSUE THREAD

**Issue by malaterre** [thorfdbg/libjpeg#64]
I am getting odd result using RGB + interleave none (line & sample seems ok). I have not been able to track the issue down so far.

Steps to reproduce:

```
% convert -depth 8 -size 512x512 xc:red red.ppm
% jpeg -ls 0 red.ppm red.jls
% jpeg red.jls red.jls.ppm
% md5sum red*ppm
0e72ce8f470bc36880c2d1a372778c25  red.jls.ppm
dc5a4219578d76b4139a691f06a39c4c  red.ppm
```

**Comment by thorfdbg** [comment]
Am 11.02.22 um 17:33 schrieb Mathieu Malaterre:
> I am getting odd result using RGB + interleave none (line & sample seems
> ok). I have not been able to track the issue down so far.

Note that this encoder/decoder operates in YUV space, by convention.
Thus, whenever you input an image in RGB space, it converts for you this
input to YUV, and on decoding back from YUV to RGB. This conversion is
not originally part of the JPEG spec, it came later with JFIF (today,
10918-5). It is, however, performed without asking because people expect
it to happen (even though not being part of the specs).

As all JPEG standards, neither JPEG nor JPEG-LS define an output color
space, and for consistency, the RGB<->YUV conversion is then also
applied to LS - the color conversion front-end is agnostic to the
compression back-end. Of course, that defeats lossless encoding and
decoding as the T.601 conversion is lossy.

To prevent that from happening, encode with the "-c" flag. This not only
turns the RGB->YUV conversion off, it also injects the Adobe RGB APP
marker which indicates to the decoder that decoding in RGB space is
desired. This will then allow you to ensure lossless decompression,
without any further flags applied.

Another option would be the "-cls" command line switch which enables a
lossless RGB<->YUV conversion. This conversion and the corresponding
marker are, however, part of JPEG-LS part 2, limiting the
interoperability of the file.

Or, as the readme puts it:

/*snip*/

Additionally, this implementation also supports JPEG LS, which is
outside of Rec. ITU-T T.81 | ISO/IEC 10918-1 and ISO/IEC 18477. For
that, use the command line option -ls:

$ jpeg -ls -c infile.ppm out.jpg

The "-c" command line switch is necessary to disable the color
transformation
as JPEG LS typically encodes in RGB and not YCbCr space.

/*snip*/

As often, reading instructions for multiple minutes can avoid hunting
bugs for some hours. (-;

Greetings,
	Thomas

**Comment by ValZapod** [comment]
I will just poi t out that even going from full YCbCr to limited R'G'B' will not be lossless. You need 10 bit YCbCr to preserve 8 bit R'G'B' and 12 for 10 R'G'B'. This is because even in full range YCbCr a lot values are outside R'G'B'.

**Comment by thorfdbg** [comment]
Am 16.02.2022 um 04:29 schrieb Valerii Zapodovnikov:
> I will just point out that even going from full YCbCr to limited R'G'B' 
> will not be lossless. You need 10 bit YCbCr to preserve 8 bit R'G'B' and 
> 12 for 10 R'G'B'. This is because even in full range YCbCr a lot values 
> are outside R'G'B'.

That's all correct because the color gamut is a different one. If you 
want lossless encoding, you need additional mechanisms, for example by 
including an additional residual in the RGB space, or by disabling the 
color transformation.

ISO/IEC 18477-8 defines the color transformation with four additional 
fractional bits, BTW, which is also what the implementation does. Thus, 
the actual decoder creates for an 8-bit codestream 12-bit data as input 
to the YUV to RGB transformation. Note that this alone is not sufficient 
to ensure lossless decoding due to the size of the gamut, as noted.

Short: That's all known and taken care of, but you need to use the right 
coding tools to ensure lossless reconstruction. The README file lists a 
couple of examples how to do that.

Greetings,
	Thomas

**Comment by malaterre** [comment]
I'll remember to never post on Friday evening. I've added the examples section directly in the man page to never forget about reading documentation:

* https://salsa.debian.org/debian-phototools-team/libjpeg/-/commit/a0a7e86ef751e9008729276ce04ce838a3e8e821

Thanks & sorry for the noise.
