### ISSUE TITLE
`jpeg` generates 12-bit JPEG with 0xFF AC Huffman symbol

### ISSUE THREAD

**Issue by leo-barnes** [thorfdbg/libjpeg#88]
Repro steps:
```
jpeg -q 10 example.pgm out_q30.jpg
```

If I do this, I get Huffman tables that look as follows:
```
('FFC4' "DHT (Define Huffman tables)", size = 308, offset = 275){
  {
    Tc = 0
    Th = 0
    L = [ 0 0 6 2 3 1 1 1 1 1 0 0 0 0 0 0 ]
    V = [
      05 06 07 08 09 0A 04 0B 02 03 0C 01 00 0D 0E 0F
    ]
  }
  {
    Tc = 1
    Th = 0
    L = [ 0 1 3 3 2 4 4 2 5 3 4 6 5 6 207 1 ]
    V = [
      01 02 03 04 05 06 11 07 12 00 08 09 21 0A 13 22
      31 14 41 0B 15 32 51 61 23 71 81 0C 16 42 91 17
      24 33 52 A1 B1 0D 62 C1 D1 F0 18 25 43 72 E1 F1
      0E 0F 10 19 1A 1B 1C 1D 1E 1F 20 26 27 28 29 2A
      2B 2C 2D 2E 2F 30 34 35 36 37 38 39 3A 3B 3C 3D
      3E 3F 40 44 45 46 47 48 49 4A 4B 4C 4D 4E 4F 50
      53 54 55 56 57 58 59 5A 5B 5C 5D 5E 5F 60 63 64
      65 66 67 68 69 6A 6B 6C 6D 6E 6F 70 73 74 75 76
      77 78 79 7A 7B 7C 7D 7E 7F 80 82 83 84 85 86 87
      88 89 8A 8B 8C 8D 8E 8F 90 92 93 94 95 96 97 98
      99 9A 9B 9C 9D 9E 9F A0 A2 A3 A4 A5 A6 A7 A8 A9
      AA AB AC AD AE AF B0 B2 B3 B4 B5 B6 B7 B8 B9 BA
      BB BC BD BE BF C0 C2 C3 C4 C5 C6 C7 C8 C9 CA CB
      CC CD CE CF D0 D2 D3 D4 D5 D6 D7 D8 D9 DA DB DC
      DD DE DF E0 E2 E3 E4 E5 E6 E7 E8 E9 EA EB EC ED
      EE EF F2 F3 F4 F5 F6 F7 F8 F9 FA FB FC FD FE FF
    ]
  }
}
```

Per section F.1.5.2 in CCITT T.81 (09/92), it looks as if the largest allowed value of `SSSS` is 14 (0xE).
I don't actually see any language in the spec that disallows having impossible codes in the table, but it seems a bit ambiguous.

[example.pgm.zip](https://github.com/thorfdbg/libjpeg/files/13238294/example.pgm.zip)

**Comment by thorfdbg** [comment]
Yes, your observation is correct. What you see here are the "default Huffman tables" that include codes for symbols that are unused in the baseline and extended Huffman case, but that are actually used in some XT extended processes like the "high bitrate case" for residual coding of large bpp cases. This way the encoder can get away with a single default table instead of multiple tables.
At this version, you can avoid the trouble (if it is one) by creating an optimized Huffman table (with the -h option) and only those symbols are included in the table that are actually used.
As you state, the standard is not very expicit whether that is permissible or not. It would be interesting to see whether that causes breakage in some implementations. Do you have further information?

**Comment by thorfdbg** [comment]
Won't fix. Work around documented if needed, though the streams should be fine.
